CSP-105-Web-ConfirmRegulatedStandard
SkillsFundingAgency/das-roatp-coursemanagement-web pull request #24
Opened 2022-06-09 13:41 UTC by raviudari01

2022-06-13 07:34 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement.Web/Controllers/StandardsController.cs
> +            model.ConfirmRegulatedStandardUrl = Url.RouteUrl(RouteNames.ConfirmRegulatedStandard, new { Ukprn, larsCode }, Request.Scheme, Request.Host.Value);
What is the purpose of Request.Scheme and Request.Host? Other url seems to be working with out adding these information.

2022-06-14 20:11 UTC, DevenKShah requested changes
Half way in review I realised that this has not been merged well, I can see changes from 122 in here

2022-06-15 07:35 UTC, MarkFCain commented on src/SFA.DAS.Roatp.CourseManagement.Application/Standard/Commands/UpdateApprovedByRegulator/UpdateApprovedByRegulatorCommandHandler.cs
> +                _logger.LogError("Failed to confirm regulated standard information request for ukprn:{ukprn} LarsCode:{larscode}", command.Ukprn, command.LarsCode);
similar note to above,, change 'confirm' to 'set approval for '

2022-06-15 07:37 UTC, MarkFCain reviewed
I've added a few optional changes to words in logs/exceptions, I'll leave it to you.  I will approve when Deven's issues are resolved

2022-06-15 07:39 UTC, MarkFCain approved these changes

2022-06-15 14:40 UTC, DevenKShah commented on src/SFA.DAS.Roatp.CourseManagement.Web/Controllers/StandardsController.cs
> +            model.ConfirmRegulatedStandardUrl = Url.RouteUrl(RouteNames.ConfirmRegulatedStandard, new { Ukprn, larsCode });
Missed check if IsRegulatedStandard

2022-06-15 15:04 UTC, DevenKShah approved these changes
Minor suggestions

2022-06-17 10:47 UTC, merged